/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CompetitionRegistry__factory } from "./CompetitionRegistry__factory";
export { RecordCertificate__factory } from "./RecordCertificate__factory";
