/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CompetitionRegistry {
  export type RecordViewStruct = {
    recordId: BigNumberish;
    competitionId: BigNumberish;
    participantId: string;
    participantWallet: AddressLike;
    recorder: AddressLike;
    recordCID: string;
    state: BigNumberish;
    createdAt: BigNumberish;
    validationCount: BigNumberish;
    encryptedTime: BytesLike;
    encryptedRank: BytesLike;
  };

  export type RecordViewStructOutput = [
    recordId: bigint,
    competitionId: bigint,
    participantId: string,
    participantWallet: string,
    recorder: string,
    recordCID: string,
    state: bigint,
    createdAt: bigint,
    validationCount: bigint,
    encryptedTime: string,
    encryptedRank: string
  ] & {
    recordId: bigint;
    competitionId: bigint;
    participantId: string;
    participantWallet: string;
    recorder: string;
    recordCID: string;
    state: bigint;
    createdAt: bigint;
    validationCount: bigint;
    encryptedTime: string;
    encryptedRank: string;
  };
}

export interface CompetitionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addValidators"
      | "challengeRecord"
      | "competitionsById"
      | "confidentialProtocolId"
      | "fetchRecord"
      | "fetchRecordsByCompetition"
      | "fetchRecordsByParticipant"
      | "getValidationCount"
      | "hasValidated"
      | "isValidatorForCompetition"
      | "nextCompetitionId"
      | "nextRecordId"
      | "recordEvidence"
      | "recordIdsByCompetition"
      | "recordIdsByParticipantHash"
      | "recordsById"
      | "registerCompetition"
      | "resolveChallenge"
      | "updateCompetitionStatus"
      | "updateCompetitionThreshold"
      | "uploadRecord"
      | "validateRecord"
      | "validatorCountForCompetition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompetitionRegistered"
      | "CompetitionUpdated"
      | "RecordChallenged"
      | "RecordStateChanged"
      | "RecordUploaded"
      | "RecordValidated"
      | "ValidatorsAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addValidators",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeRecord",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "competitionsById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchRecordsByCompetition",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchRecordsByParticipant",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValidated",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidatorForCompetition",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCompetitionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextRecordId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordEvidence",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordIdsByCompetition",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordIdsByParticipantHash",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordsById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCompetition",
    values: [string, BigNumberish, BigNumberish, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveChallenge",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCompetitionStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCompetitionThreshold",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadRecord",
    values: [
      BigNumberish,
      string,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateRecord",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorCountForCompetition",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "competitionsById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchRecordsByCompetition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchRecordsByParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasValidated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidatorForCompetition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCompetitionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRecordId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordIdsByCompetition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordIdsByParticipantHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordsById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCompetition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCompetitionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCompetitionThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorCountForCompetition",
    data: BytesLike
  ): Result;
}

export namespace CompetitionRegisteredEvent {
  export type InputTuple = [
    competitionId: BigNumberish,
    host: AddressLike,
    metadataCID: string
  ];
  export type OutputTuple = [
    competitionId: bigint,
    host: string,
    metadataCID: string
  ];
  export interface OutputObject {
    competitionId: bigint;
    host: string;
    metadataCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompetitionUpdatedEvent {
  export type InputTuple = [
    competitionId: BigNumberish,
    isActive: boolean,
    requiredConfirmations: BigNumberish
  ];
  export type OutputTuple = [
    competitionId: bigint,
    isActive: boolean,
    requiredConfirmations: bigint
  ];
  export interface OutputObject {
    competitionId: bigint;
    isActive: boolean;
    requiredConfirmations: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordChallengedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    challenger: AddressLike,
    challengeCID: string
  ];
  export type OutputTuple = [
    recordId: bigint,
    challenger: string,
    challengeCID: string
  ];
  export interface OutputObject {
    recordId: bigint;
    challenger: string;
    challengeCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordStateChangedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    oldState: BigNumberish,
    newState: BigNumberish
  ];
  export type OutputTuple = [
    recordId: bigint,
    oldState: bigint,
    newState: bigint
  ];
  export interface OutputObject {
    recordId: bigint;
    oldState: bigint;
    newState: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordUploadedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    competitionId: BigNumberish,
    participantId: string,
    recorder: AddressLike,
    recordCID: string
  ];
  export type OutputTuple = [
    recordId: bigint,
    competitionId: bigint,
    participantId: string,
    recorder: string,
    recordCID: string
  ];
  export interface OutputObject {
    recordId: bigint;
    competitionId: bigint;
    participantId: string;
    recorder: string;
    recordCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordValidatedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    validator: AddressLike,
    approved: boolean,
    evidenceCID: string
  ];
  export type OutputTuple = [
    recordId: bigint,
    validator: string,
    approved: boolean,
    evidenceCID: string
  ];
  export interface OutputObject {
    recordId: bigint;
    validator: string;
    approved: boolean;
    evidenceCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorsAddedEvent {
  export type InputTuple = [
    competitionId: BigNumberish,
    validators: AddressLike[]
  ];
  export type OutputTuple = [competitionId: bigint, validators: string[]];
  export interface OutputObject {
    competitionId: bigint;
    validators: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CompetitionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CompetitionRegistry;
  waitForDeployment(): Promise<this>;

  interface: CompetitionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addValidators: TypedContractMethod<
    [competitionId: BigNumberish, validators: AddressLike[]],
    [void],
    "nonpayable"
  >;

  challengeRecord: TypedContractMethod<
    [recordId: BigNumberish, challengeCID: string],
    [void],
    "nonpayable"
  >;

  competitionsById: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint] & {
        competitionId: bigint;
        host: string;
        metadataCID: string;
        beginTime: bigint;
        finishTime: bigint;
        isActive: boolean;
        requiredConfirmations: bigint;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  fetchRecord: TypedContractMethod<
    [recordId: BigNumberish],
    [CompetitionRegistry.RecordViewStructOutput],
    "view"
  >;

  fetchRecordsByCompetition: TypedContractMethod<
    [competitionId: BigNumberish, start: BigNumberish, count: BigNumberish],
    [CompetitionRegistry.RecordViewStructOutput[]],
    "view"
  >;

  fetchRecordsByParticipant: TypedContractMethod<
    [participantId: string],
    [bigint[]],
    "view"
  >;

  getValidationCount: TypedContractMethod<
    [recordId: BigNumberish],
    [bigint],
    "view"
  >;

  hasValidated: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isValidatorForCompetition: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  nextCompetitionId: TypedContractMethod<[], [bigint], "view">;

  nextRecordId: TypedContractMethod<[], [bigint], "view">;

  recordEvidence: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  recordIdsByCompetition: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  recordIdsByParticipantHash: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  recordsById: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        recordId: bigint;
        competitionId: bigint;
        participantId: string;
        participantWallet: string;
        recorder: string;
        recordCID: string;
        state: bigint;
        createdAt: bigint;
        validationCount: bigint;
        encryptedTime: string;
        encryptedRank: string;
      }
    ],
    "view"
  >;

  registerCompetition: TypedContractMethod<
    [
      metadataCID: string,
      beginTime: BigNumberish,
      finishTime: BigNumberish,
      requiredConfirmations: BigNumberish,
      validators: AddressLike[]
    ],
    [bigint],
    "nonpayable"
  >;

  resolveChallenge: TypedContractMethod<
    [recordId: BigNumberish, uphold: boolean, arg2: string],
    [void],
    "nonpayable"
  >;

  updateCompetitionStatus: TypedContractMethod<
    [competitionId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;

  updateCompetitionThreshold: TypedContractMethod<
    [competitionId: BigNumberish, requiredConfirmations: BigNumberish],
    [void],
    "nonpayable"
  >;

  uploadRecord: TypedContractMethod<
    [
      competitionId: BigNumberish,
      participantId: string,
      participantWallet: AddressLike,
      encryptedTimeExt: BytesLike,
      proofTime: BytesLike,
      encryptedRankExt: BytesLike,
      proofRank: BytesLike,
      recordCID: string
    ],
    [bigint],
    "nonpayable"
  >;

  validateRecord: TypedContractMethod<
    [recordId: BigNumberish, approved: boolean, evidenceCID: string],
    [void],
    "nonpayable"
  >;

  validatorCountForCompetition: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addValidators"
  ): TypedContractMethod<
    [competitionId: BigNumberish, validators: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "challengeRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish, challengeCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "competitionsById"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint] & {
        competitionId: bigint;
        host: string;
        metadataCID: string;
        beginTime: bigint;
        finishTime: bigint;
        isActive: boolean;
        requiredConfirmations: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fetchRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [CompetitionRegistry.RecordViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "fetchRecordsByCompetition"
  ): TypedContractMethod<
    [competitionId: BigNumberish, start: BigNumberish, count: BigNumberish],
    [CompetitionRegistry.RecordViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "fetchRecordsByParticipant"
  ): TypedContractMethod<[participantId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getValidationCount"
  ): TypedContractMethod<[recordId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasValidated"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidatorForCompetition"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextCompetitionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextRecordId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordEvidence"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordIdsByCompetition"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordIdsByParticipantHash"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordsById"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        recordId: bigint;
        competitionId: bigint;
        participantId: string;
        participantWallet: string;
        recorder: string;
        recordCID: string;
        state: bigint;
        createdAt: bigint;
        validationCount: bigint;
        encryptedTime: string;
        encryptedRank: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerCompetition"
  ): TypedContractMethod<
    [
      metadataCID: string,
      beginTime: BigNumberish,
      finishTime: BigNumberish,
      requiredConfirmations: BigNumberish,
      validators: AddressLike[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveChallenge"
  ): TypedContractMethod<
    [recordId: BigNumberish, uphold: boolean, arg2: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCompetitionStatus"
  ): TypedContractMethod<
    [competitionId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCompetitionThreshold"
  ): TypedContractMethod<
    [competitionId: BigNumberish, requiredConfirmations: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadRecord"
  ): TypedContractMethod<
    [
      competitionId: BigNumberish,
      participantId: string,
      participantWallet: AddressLike,
      encryptedTimeExt: BytesLike,
      proofTime: BytesLike,
      encryptedRankExt: BytesLike,
      proofRank: BytesLike,
      recordCID: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish, approved: boolean, evidenceCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validatorCountForCompetition"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "CompetitionRegistered"
  ): TypedContractEvent<
    CompetitionRegisteredEvent.InputTuple,
    CompetitionRegisteredEvent.OutputTuple,
    CompetitionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CompetitionUpdated"
  ): TypedContractEvent<
    CompetitionUpdatedEvent.InputTuple,
    CompetitionUpdatedEvent.OutputTuple,
    CompetitionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RecordChallenged"
  ): TypedContractEvent<
    RecordChallengedEvent.InputTuple,
    RecordChallengedEvent.OutputTuple,
    RecordChallengedEvent.OutputObject
  >;
  getEvent(
    key: "RecordStateChanged"
  ): TypedContractEvent<
    RecordStateChangedEvent.InputTuple,
    RecordStateChangedEvent.OutputTuple,
    RecordStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "RecordUploaded"
  ): TypedContractEvent<
    RecordUploadedEvent.InputTuple,
    RecordUploadedEvent.OutputTuple,
    RecordUploadedEvent.OutputObject
  >;
  getEvent(
    key: "RecordValidated"
  ): TypedContractEvent<
    RecordValidatedEvent.InputTuple,
    RecordValidatedEvent.OutputTuple,
    RecordValidatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorsAdded"
  ): TypedContractEvent<
    ValidatorsAddedEvent.InputTuple,
    ValidatorsAddedEvent.OutputTuple,
    ValidatorsAddedEvent.OutputObject
  >;

  filters: {
    "CompetitionRegistered(uint256,address,string)": TypedContractEvent<
      CompetitionRegisteredEvent.InputTuple,
      CompetitionRegisteredEvent.OutputTuple,
      CompetitionRegisteredEvent.OutputObject
    >;
    CompetitionRegistered: TypedContractEvent<
      CompetitionRegisteredEvent.InputTuple,
      CompetitionRegisteredEvent.OutputTuple,
      CompetitionRegisteredEvent.OutputObject
    >;

    "CompetitionUpdated(uint256,bool,uint8)": TypedContractEvent<
      CompetitionUpdatedEvent.InputTuple,
      CompetitionUpdatedEvent.OutputTuple,
      CompetitionUpdatedEvent.OutputObject
    >;
    CompetitionUpdated: TypedContractEvent<
      CompetitionUpdatedEvent.InputTuple,
      CompetitionUpdatedEvent.OutputTuple,
      CompetitionUpdatedEvent.OutputObject
    >;

    "RecordChallenged(uint256,address,string)": TypedContractEvent<
      RecordChallengedEvent.InputTuple,
      RecordChallengedEvent.OutputTuple,
      RecordChallengedEvent.OutputObject
    >;
    RecordChallenged: TypedContractEvent<
      RecordChallengedEvent.InputTuple,
      RecordChallengedEvent.OutputTuple,
      RecordChallengedEvent.OutputObject
    >;

    "RecordStateChanged(uint256,uint8,uint8)": TypedContractEvent<
      RecordStateChangedEvent.InputTuple,
      RecordStateChangedEvent.OutputTuple,
      RecordStateChangedEvent.OutputObject
    >;
    RecordStateChanged: TypedContractEvent<
      RecordStateChangedEvent.InputTuple,
      RecordStateChangedEvent.OutputTuple,
      RecordStateChangedEvent.OutputObject
    >;

    "RecordUploaded(uint256,uint256,string,address,string)": TypedContractEvent<
      RecordUploadedEvent.InputTuple,
      RecordUploadedEvent.OutputTuple,
      RecordUploadedEvent.OutputObject
    >;
    RecordUploaded: TypedContractEvent<
      RecordUploadedEvent.InputTuple,
      RecordUploadedEvent.OutputTuple,
      RecordUploadedEvent.OutputObject
    >;

    "RecordValidated(uint256,address,bool,string)": TypedContractEvent<
      RecordValidatedEvent.InputTuple,
      RecordValidatedEvent.OutputTuple,
      RecordValidatedEvent.OutputObject
    >;
    RecordValidated: TypedContractEvent<
      RecordValidatedEvent.InputTuple,
      RecordValidatedEvent.OutputTuple,
      RecordValidatedEvent.OutputObject
    >;

    "ValidatorsAdded(uint256,address[])": TypedContractEvent<
      ValidatorsAddedEvent.InputTuple,
      ValidatorsAddedEvent.OutputTuple,
      ValidatorsAddedEvent.OutputObject
    >;
    ValidatorsAdded: TypedContractEvent<
      ValidatorsAddedEvent.InputTuple,
      ValidatorsAddedEvent.OutputTuple,
      ValidatorsAddedEvent.OutputObject
    >;
  };
}
