/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompetitionRegistry } from "./CompetitionRegistry";
export type { RecordCertificate } from "./RecordCertificate";
